[programs.localnet]
named_mints = "2TNhak2qKeY9YhfTSrooFFGqssU5DeUb2WjAJ653S57c"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/nathanshirley/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
